spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MySQL;
    username: sa
    password:
#    initialization-mode: always
#    schema: schema-h2.sql
#    data: data-h2.sql

  h2:
    console:
      enabled: true

  jpa:
    database: h2
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: create-drop